### ISSUE TITLE
Are you still actively maintaining this repo?

### ISSUE THREAD

**Issue by mikemellor11** [raygesualdo/grunt-scorm-manifest#5]
I want to add some features, but if this repo is now inactive i might just clone it and use it as a starting point for my own plugin.

**Comment by raygesualdo** [comment]
Hi @mikemellor11, I am not maintaining it anymore. Feel free to use it to start your own, or I can add you as a contributor here if you'd like to take ownership of the repo.

**Comment by mikemellor11** [comment]
Hey, good to know, well i'm using my fork quite heavily on a few projects, i'd preferably like to pull my changes into this repo and point my package.json back at the main npm package. So yeah if you wouldn't mind adding me as a contrib i'd love to help out when i get a second.
